=== GeoscienceAustralia/DynAdjust/sampleData/DynaML.xsd
<?xml version="1.1" encoding="UTF-8" standalone="yes"?>
<!-- Description:  W3C Schema for DynAdjust -->
<!-- Created by:   Roger Fraser -->
<!-- Date:         01.06.2020 -->
<!-- Version:      1.0.2 -->
<!-- Changes:      Now includes Measurement ID and Cluster ID -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Clusterpoint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="X"/>
				<xs:element ref="Y"/>
				<xs:element ref="Z"/>
				<xs:element ref="MeasurementID" minOccurs="0"/>
				<xs:element ref="SigmaXX"/>
				<xs:element ref="SigmaXY"/>
				<xs:element ref="SigmaXZ"/>
				<xs:element ref="SigmaYY"/>
				<xs:element ref="SigmaYZ"/>
				<xs:element ref="SigmaZZ"/>
				<xs:element ref="PointCovariance" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Constraints" type="xs:string"/>
	<xs:element name="Coords" type="xs:string"/>
	<xs:element name="Description" type="xs:string"/>
	<xs:element name="Directions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ignore"/>
				<xs:element ref="Target"/>
				<xs:element ref="Value"/>
				<xs:element ref="StdDev"/>
				<xs:element ref="MeasurementID" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DnaMeasurement">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="Type"/>
				<xs:element ref="Ignore" minOccurs="0"/>
				<xs:element ref="ReferenceFrame" minOccurs="0"/>
				<xs:element ref="Epoch" minOccurs="0"/>
				<xs:element ref="EpochOfObservation" minOccurs="0"/>
				<xs:element ref="First"/>
				<xs:element ref="Second"/>
				<xs:element ref="Third"/>
				<xs:element ref="Value"/>
				<xs:element ref="StdDev"/>
				<xs:element ref="InstHeight"/>
				<xs:element ref="TargHeight"/>
				<xs:element ref="Total"/>
				<xs:element ref="Directions"/>
				<xs:element ref="Vscale"/>
				<xs:element ref="GPSBaseline"/>
				<xs:element ref="Hscale" minOccurs="0"/>
				<xs:element ref="Lscale" minOccurs="0"/>
				<xs:element ref="Pscale" minOccurs="0"/>
				<xs:element ref="Clusterpoint"/>
				<xs:element ref="Coords"/>
				<xs:element ref="Source" minOccurs="0"/>
				<xs:element ref="MeasurementID" minOccurs="0"/>
				<xs:element ref="ClusterID" minOccurs="0"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="DnaStation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Constraints"/>
				<xs:element ref="Type"/>
				<xs:element ref="StationCoord"/>
				<xs:element ref="Description" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DnaXmlFormat">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="DnaStation"/>
				<xs:element ref="DnaMeasurement"/>
			</xs:choice>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Measurement File"/>
						<xs:enumeration value="Station File"/>
						<xs:enumeration value="Combined File"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="referenceframe" type="xs:string" use="optional" default="GDA2020"/>
			<xs:attribute name="epoch" type="xs:string" use="optional" default="01.01.2020"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="First" type="xs:string"/>
	<xs:element name="GPSBaseline">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="X"/>
				<xs:element ref="Y"/>
				<xs:element ref="Z"/>
				<xs:element ref="MeasurementID" minOccurs="0"/>
				<xs:element ref="SigmaXX"/>
				<xs:element ref="SigmaXY"/>
				<xs:element ref="SigmaXZ"/>
				<xs:element ref="SigmaYY"/>
				<xs:element ref="SigmaYZ"/>
				<xs:element ref="SigmaZZ"/>
				<xs:element ref="GPSCovariance" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GPSCovariance">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="m11"/>
				<xs:element ref="m12"/>
				<xs:element ref="m13"/>
				<xs:element ref="m21"/>
				<xs:element ref="m22"/>
				<xs:element ref="m23"/>
				<xs:element ref="m31"/>
				<xs:element ref="m32"/>
				<xs:element ref="m33"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Height" type="xs:string"/>
	<xs:element name="HemisphereZone" type="xs:string"/>
	<xs:element name="Hscale" type="xs:string"/>
	<xs:element name="Ignore" type="xs:string"/>
	<xs:element name="InstHeight" type="xs:string"/>
	<xs:element name="Lscale" type="xs:string"/>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="PointCovariance">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="m11"/>
				<xs:element ref="m12"/>
				<xs:element ref="m13"/>
				<xs:element ref="m21"/>
				<xs:element ref="m22"/>
				<xs:element ref="m23"/>
				<xs:element ref="m31"/>
				<xs:element ref="m32"/>
				<xs:element ref="m33"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Pscale" type="xs:string"/>
	<xs:element name="Second" type="xs:string"/>
	<xs:element name="SigmaXX" type="xs:string"/>
	<xs:element name="SigmaXY" type="xs:string"/>
	<xs:element name="SigmaXZ" type="xs:string"/>
	<xs:element name="SigmaYY" type="xs:string"/>
	<xs:element name="SigmaYZ" type="xs:string"/>
	<xs:element name="SigmaZZ" type="xs:string"/>
	<xs:element name="StationCoord">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="XAxis"/>
				<xs:element ref="YAxis"/>
				<xs:element ref="Height"/>
				<xs:element ref="HemisphereZone" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StdDev" type="xs:string"/>
	<xs:element name="TargHeight" type="xs:string"/>
	<xs:element name="Target" type="xs:string"/>
	<xs:element name="Third" type="xs:string"/>
	<xs:element name="Total" type="xs:string"/>
	<xs:element name="Type" type="xs:string"/>
	<xs:element name="Value" type="xs:string"/>
	<xs:element name="Vscale" type="xs:string"/>
	<xs:element name="X" type="xs:string"/>
	<xs:element name="XAxis" type="xs:string"/>
	<xs:element name="Y" type="xs:string"/>
	<xs:element name="YAxis" type="xs:string"/>
	<xs:element name="Z" type="xs:string"/>
	<xs:element name="m11" type="xs:string"/>
	<xs:element name="m12" type="xs:string"/>
	<xs:element name="m13" type="xs:string"/>
	<xs:element name="m21" type="xs:string"/>
	<xs:element name="m22" type="xs:string"/>
	<xs:element name="m23" type="xs:string"/>
	<xs:element name="m31" type="xs:string"/>
	<xs:element name="m32" type="xs:string"/>
	<xs:element name="m33" type="xs:string"/>
	<xs:element name="Source" type="xs:string"/>
	<xs:element name="ReferenceFrame" type="xs:string"/>
	<xs:element name="Epoch" type="xs:string"/>
	<xs:element name="EpochOfObservation" type="xs:string"/>
	<xs:element name="MeasurementID" type="xs:string"/>
	<xs:element name="ClusterID" type="xs:string"/>
</xs:schema>

=== GeoscienceAustralia/DynAdjust/sampleData/sa-gnss-stn.xml
<?xml version="1.0"?>
<DnaXmlFormat type="Station File" referenceframe="GDA2020" epoch="01.01.2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DynaML.xsd">
<!-- Created by:   dnaimport, File import and format exchange software -->
<!-- Version:      1.1.0, Release -->
<!-- Project name: Sample measurements connected to ALIC and AU001 -->
<!-- Source files: apref20200328.snx stn/SA_GDA2020_20200713.adj.xml  -->
  <DnaStation>
    <Name>ADE1</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>ADE1</Name>
      <XAxis>-3939182.8428</XAxis>
      <YAxis>3467075.3659</YAxis>
      <Height>-3613219.8375</Height>
    </StationCoord>
    <Description>ADE1</Description>
  </DnaStation>
  <DnaStation>
    <Name>PERT</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>PERT</Name>
      <XAxis>-2368688.0415</XAxis>
      <YAxis>4881316.6866</YAxis>
      <Height>-3341794.9754</Height>
    </StationCoord>
    <Description>PERT</Description>
  </DnaStation>
  <DnaStation>
    <Name>WARA</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>WARA</Name>
      <XAxis>-3583757.5894</XAxis>
      <YAxis>4538446.7027</YAxis>
      <Height>-2683056.6932</Height>
    </StationCoord>
    <Description>WARA</Description>
  </DnaStation>
  <DnaStation>
    <Name>ALIC</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>ALIC</Name>
      <XAxis>-4052052.7379</XAxis>
      <YAxis>4212835.9824</YAxis>
      <Height>-2545104.5871</Height>
    </StationCoord>
    <Description>ALIC</Description>
  </DnaStation>
  <DnaStation>
    <Name>4936/ 1009</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>4936/ 1009</Name>
      <XAxis>-3560604.3794</XAxis>
      <YAxis>4183987.5565</YAxis>
      <Height>-3229248.1005</Height>
    </StationCoord>
    <Description></Description>
  </DnaStation>
  <DnaStation>
    <Name>5035/ 1002</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>5035/ 1002</Name>
      <XAxis>-3569582.3546</XAxis>
      <YAxis>4114330.6371</YAxis>
      <Height>-3307237.2190</Height>
    </StationCoord>
    <Description></Description>
  </DnaStation>
  <DnaStation>
    <Name>5145/ 1020</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>5145/ 1020</Name>
      <XAxis>-3786311.5427</XAxis>
      <YAxis>4288090.6748</YAxis>
      <Height>-2812796.2259</Height>
    </StationCoord>
    <Description></Description>
  </DnaStation>
  <DnaStation>
    <Name>5237/ 1004</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>5237/ 1004</Name>
      <XAxis>-3671003.4278</XAxis>
      <YAxis>4099412.5424</YAxis>
      <Height>-3214180.7941</Height>
    </StationCoord>
    <Description></Description>
  </DnaStation>
  <DnaStation>
    <Name>5736/ 1044</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>5736/ 1044</Name>
      <XAxis>-3826897.6855</XAxis>
      <YAxis>3937198.4225</YAxis>
      <Height>-3235007.7711</Height>
    </StationCoord>
    <Description></Description>
  </DnaStation>
  <DnaStation>
    <Name>AU001</Name>
    <Constraints>FFF</Constraints>
    <Type>LLH</Type>
    <StationCoord>
      <Name>AU001</Name>
      <XAxis>-23.4532366108</XAxis>
      <YAxis>133.5257273702</YAxis>
      <Height>556.0946</Height>
    </StationCoord>
    <Description>AU001</Description>
  </DnaStation>
  <DnaStation>
    <Name>ALIC</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>ALIC</Name>
      <XAxis>-4052052.7417</XAxis>
      <YAxis>4212835.9885</YAxis>
      <Height>-2545104.5928</Height>
    </StationCoord>
    <Description>ALIC</Description>
  </DnaStation>
</DnaXmlFormat>

=== GeoscienceAustralia/DynAdjust/sampleData/stn_allignored.xml
<?xml version='1.0' encoding='UTF-8'?>
<DnaXmlFormat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="Station File" xsi:noNamespaceSchemaLocation="DynaML.xsd" referenceframe="GDA2020" epoch="01.01.2020">
  <DnaStation>
    <Name>327000199856</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000199856</Name>
      <XAxis>266590.8352</XAxis>
      <YAxis>5782831.0281</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000200130</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000200130</Name>
      <XAxis>266594.4766</XAxis>
      <YAxis>5782860.3525</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000200447</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000200447</Name>
      <XAxis>266599.4726</XAxis>
      <YAxis>5782864.0945</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000200835</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000200835</Name>
      <XAxis>266606.6443</XAxis>
      <YAxis>5782829.0209</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000201157</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000201157</Name>
      <XAxis>266610.6108</XAxis>
      <YAxis>5782862.7487</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000201926</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000201926</Name>
      <XAxis>266622.4093</XAxis>
      <YAxis>5782827.0212</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000202572</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000202572</Name>
      <XAxis>266626.5750</XAxis>
      <YAxis>5782860.8181</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000204449</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000204449</Name>
      <XAxis>266638.2263</XAxis>
      <YAxis>5782825.0130</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000205365</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000205365</Name>
      <XAxis>266642.3434</XAxis>
      <YAxis>5782858.9129</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000206876</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000206876</Name>
      <XAxis>266653.8291</XAxis>
      <YAxis>5782823.0331</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327000207246</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327000207246</Name>
      <XAxis>266658.1312</XAxis>
      <YAxis>5782857.0049</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327500273624</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327500273624</Name>
      <XAxis>266618.9543</XAxis>
      <YAxis>5782827.3973</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327500273625</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327500273625</Name>
      <XAxis>266618.9581</XAxis>
      <YAxis>5782827.4273</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
  <DnaStation>
    <Name>327500273626</Name>
    <Constraints>FFC</Constraints>
    <Type>UTM</Type>
    <StationCoord>
      <Name>327500273626</Name>
      <XAxis>266595.1108</XAxis>
      <YAxis>5782864.7506</YAxis>
      <Height>0.0000</Height>
      <HemisphereZone>S55</HemisphereZone>
    </StationCoord>
  </DnaStation>
</DnaXmlFormat>

=== GeoscienceAustralia/DynAdjust/sampleData/source-test-stn.xml
<?xml version="1.0"?>
<DnaXmlFormat type="Station File" referenceframe="GDA2020" epoch="01.01.2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DynaML.xsd">
  <DnaStation>
    <Name>ALIC</Name>
    <Constraints>CCC</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>ALIC</Name>
      <XAxis>-4052052.7379</XAxis>
      <YAxis>4212835.9824</YAxis>
      <Height>-2545104.5871</Height>
    </StationCoord>
    <Description>ALIC</Description>
  </DnaStation>
  <DnaStation>
    <Name>WARA</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>WARA</Name>
      <XAxis>-3583757.5894</XAxis>
      <YAxis>4538446.7027</YAxis>
      <Height>-2683056.6932</Height>
    </StationCoord>
    <Description>WARA</Description>
  </DnaStation>
  <DnaStation>
    <Name>ADE1</Name>
    <Constraints>FFF</Constraints>
    <Type>XYZ</Type>
    <StationCoord>
      <Name>ADE1</Name>
      <XAxis>-3939182.8428</XAxis>
      <YAxis>3467075.3659</YAxis>
      <Height>-3613219.8375</Height>
    </StationCoord>
    <Description>ADE1</Description>
  </DnaStation>
</DnaXmlFormat>

=== GeoscienceAustralia/DynAdjust/sampleData/source-test-msr.xml
<?xml version="1.0"?>
<DnaXmlFormat type="Measurement File" referenceframe="GDA2020" epoch="01.01.2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DynaML.xsd">
  <DnaMeasurement>
    <Type>G</Type>
    <Source>CAMPAIGN_2023A</Source>
    <Ignore/>
    <ReferenceFrame>GDA2020</ReferenceFrame>
    <Epoch>01.01.2020</Epoch>
    <Vscale>1.000</Vscale>
    <Pscale>1.000</Pscale>
    <Lscale>1.000</Lscale>
    <Hscale>1.000</Hscale>
    <First>ALIC</First>
    <Second>WARA</Second>
    <GPSBaseline>
      <X>468295.1485</X>
      <Y>325610.7203</Y>
      <Z>-137952.1061</Z>
      <SigmaXX>1.7012598619e-005</SigmaXX>
      <SigmaXY>-1.0467927495e-005</SigmaXY>
      <SigmaXZ>1.4195195035e-005</SigmaXZ>
      <SigmaYY>9.4335882750e-006</SigmaYY>
      <SigmaYZ>-1.0196034054e-005</SigmaYZ>
      <SigmaZZ>1.4284143617e-005</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
  <DnaMeasurement>
    <Type>G</Type>
    <Source>CAMPAIGN_2023B</Source>
    <Ignore/>
    <ReferenceFrame>GDA2020</ReferenceFrame>
    <Epoch>01.01.2020</Epoch>
    <Vscale>1.000</Vscale>
    <Pscale>1.000</Pscale>
    <Lscale>1.000</Lscale>
    <Hscale>1.000</Hscale>
    <First>ALIC</First>
    <Second>ADE1</Second>
    <GPSBaseline>
      <X>112869.8951</X>
      <Y>-745760.6165</Y>
      <Z>-1068115.2504</Z>
      <SigmaXX>1.7457261805e-006</SigmaXX>
      <SigmaXY>-1.0335401280e-006</SigmaXY>
      <SigmaXZ>9.1178422963e-007</SigmaXZ>
      <SigmaYY>1.4855548902e-006</SigmaYY>
      <SigmaYZ>-8.8699137178e-007</SigmaYZ>
      <SigmaZZ>8.9829335174e-007</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
  <DnaMeasurement>
    <Type>G</Type>
    <Source></Source>
    <Ignore/>
    <ReferenceFrame>GDA2020</ReferenceFrame>
    <Epoch>01.01.2020</Epoch>
    <Vscale>1.000</Vscale>
    <Pscale>1.000</Pscale>
    <Lscale>1.000</Lscale>
    <Hscale>1.000</Hscale>
    <First>WARA</First>
    <Second>ADE1</Second>
    <GPSBaseline>
      <X>-355425.2534</X>
      <Y>-1071371.3368</Y>
      <Z>-930163.1443</Z>
      <SigmaXX>2.5012598619e-005</SigmaXX>
      <SigmaXY>-1.2467927495e-005</SigmaXY>
      <SigmaXZ>1.6195195035e-005</SigmaXZ>
      <SigmaYY>1.1433588275e-005</SigmaYY>
      <SigmaYZ>-1.2196034054e-005</SigmaYZ>
      <SigmaZZ>1.6284143617e-005</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
</DnaXmlFormat>

=== GeoscienceAustralia/DynAdjust/sampleData/sa-gnss-msr.xml
<?xml version="1.0"?>
<DnaXmlFormat type="Measurement File" referenceframe="GDA2020" epoch="01.01.2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DynaML.xsd">
<!-- Created by:   dnaimport, File import and format exchange software -->
<!-- File type:    Measurement file -->
<!-- Project name: Sample measurements connected to ALIC and AU001 -->
<!-- Source files: SA_NGCA_20200706_msr.xml SA_SZS_20190521_msr.xml SA20200713_msr.xml  -->  
  <!-- Type (X) GPS baseline cluster (set of 2) -->
  <DnaMeasurement>
    <Type>X</Type>
    <Source></Source>
    <Ignore/>
    <ReferenceFrame>GDA2020</ReferenceFrame>
    <Epoch>01.01.2020</Epoch>
    <Vscale>26.334</Vscale>
    <Pscale>1.000</Pscale>
    <Lscale>1.000</Lscale>
    <Hscale>1.000</Hscale>
    <Total>2</Total>
    <First>5145/ 1020</First>
    <Second>ALIC</Second>
    <GPSBaseline>
      <X>-265741.1992</X>
      <Y>-75254.6860</Y>
      <Z>267691.6337</Z>
      <SigmaXX>3.1692911215074e-06</SigmaXX>
      <SigmaXY>-3.0189295562249e-06</SigmaXY>
      <SigmaXZ>1.8040563153590e-06</SigmaXZ>
      <SigmaYY>3.6084303774150e-06</SigmaYY>
      <SigmaYZ>-1.9983840440961e-06</SigmaYZ>
      <SigmaZZ>1.6272934642743e-06</SigmaZZ>
      <GPSCovariance>
        <m11>1.9785693970757e-06</m11>
        <m12>-1.9362240579981e-06</m12>
        <m13>1.1841269024510e-06</m13>
        <m21>-1.9312412228592e-06</m21>
        <m22>2.2898553689497e-06</m22>
        <m23>-1.3181086176743e-06</m23>
        <m31>1.1869579872882e-06</m31>
        <m32>-1.3263830801569e-06</m32>
        <m33>1.0671586707975e-06</m33>
      </GPSCovariance>
    </GPSBaseline>
    <First>5145/ 1020</First>
    <Second>WARA</Second>
    <GPSBaseline>
      <X>202553.9537</X>
      <Y>250356.0273</Y>
      <Z>129739.5309</Z>
      <SigmaXX>3.1524300462309e-06</SigmaXX>
      <SigmaXY>-3.1167951990447e-06</SigmaXY>
      <SigmaXZ>1.8614611111476e-06</SigmaXZ>
      <SigmaYY>3.8074723329251e-06</SigmaYY>
      <SigmaYZ>-2.1320534175385e-06</SigmaYZ>
      <SigmaZZ>1.6945695825399e-06</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
  <!-- Type (X) GPS baseline cluster (set of 3) -->
  <DnaMeasurement>
    <Type>X</Type>
    <Source></Source>
    <Ignore/>
    <ReferenceFrame>GDA2020</ReferenceFrame>
    <Epoch>01.01.2020</Epoch>
    <Vscale>21.061</Vscale>
    <Pscale>1.000</Pscale>
    <Lscale>1.000</Lscale>
    <Hscale>1.000</Hscale>
    <Total>3</Total>
    <First>5237/ 1004</First>
    <Second>4936/ 1009</Second>
    <GPSBaseline>
      <X>110399.0306</X>
      <Y>84575.0404</Y>
      <Z>-15067.3215</Z>
      <SigmaXX>6.9233761056271e-06</SigmaXX>
      <SigmaXY>-7.0296468447316e-06</SigmaXY>
      <SigmaXZ>5.0508066495701e-06</SigmaXZ>
      <SigmaYY>8.5103968220681e-06</SigmaYY>
      <SigmaYZ>-5.6723677598659e-06</SigmaYZ>
      <SigmaZZ>5.0314334159837e-06</SigmaZZ>
      <GPSCovariance>
        <m11>3.1659227664281e-06</m11>
        <m12>-3.1718355656881e-06</m12>
        <m13>2.2827466929588e-06</m13>
        <m21>-3.2010502472121e-06</m21>
        <m22>3.8213693568111e-06</m22>
        <m23>-2.5463949726556e-06</m23>
        <m31>2.2837508937488e-06</m31>
        <m32>-2.5212259771630e-06</m32>
        <m33>2.2429579863440e-06</m33>
      </GPSCovariance>
      <GPSCovariance>
        <m11>3.1862571385733e-06</m11>
        <m12>-3.2168075475174e-06</m12>
        <m13>2.2920390528121e-06</m13>
        <m21>-3.2352191213462e-06</m21>
        <m22>3.8932143972889e-06</m22>
        <m23>-2.5633452067864e-06</m23>
        <m31>2.2993416770459e-06</m31>
        <m32>-2.5546762090567e-06</m32>
        <m33>2.2532807810070e-06</m33>
      </GPSCovariance>
    </GPSBaseline>
    <First>5237/ 1004</First>
    <Second>ALIC</Second>
    <GPSBaseline>
      <X>-381049.3398</X>
      <Y>113423.4769</Y>
      <Z>669076.1793</Z>
      <SigmaXX>5.3507829701698e-06</SigmaXX>
      <SigmaXY>-5.1155919064744e-06</SigmaXY>
      <SigmaXZ>3.5457405468555e-06</SigmaXZ>
      <SigmaYY>6.0376419076352e-06</SigmaYY>
      <SigmaYZ>-3.8168553392316e-06</SigmaYZ>
      <SigmaZZ>3.3732941186705e-06</SigmaZZ>
      <GPSCovariance>
        <m11>3.9648197619218e-06</m11>
        <m12>-4.0656166403647e-06</m12>
        <m13>2.8237633319837e-06</m13>
        <m21>-3.9570893725201e-06</m21>
        <m22>4.7501198268852e-06</m22>
        <m23>-3.0794564131509e-06</m23>
        <m31>2.8174725421786e-06</m31>
        <m32>-3.1619681313492e-06</m32>
        <m33>2.6504174433878e-06</m33>
      </GPSCovariance>
    </GPSBaseline>
    <First>5237/ 1004</First>
    <Second>PERT</Second>
    <GPSBaseline>
      <X>1302315.3465</X>
      <Y>781904.2071</Y>
      <Z>-127614.2257</Z>
      <SigmaXX>5.2103396073406e-06</SigmaXX>
      <SigmaXY>-5.5714491933789e-06</SigmaXY>
      <SigmaXZ>3.7151261436950e-06</SigmaXZ>
      <SigmaYY>7.6888673603155e-06</SigmaYY>
      <SigmaYZ>-4.7307952136039e-06</SigmaYZ>
      <SigmaZZ>3.9549354435854e-06</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
  <!-- Type (X) GPS baseline cluster (set of 3) -->
  <DnaMeasurement>
    <Type>X</Type>
    <Source></Source>
    <Ignore/>
    <ReferenceFrame>GDA2020</ReferenceFrame>
    <Epoch>01.01.2020</Epoch>
    <Vscale>34.663</Vscale>
    <Pscale>1.000</Pscale>
    <Lscale>1.000</Lscale>
    <Hscale>1.000</Hscale>
    <Total>3</Total>
    <First>5035/ 1002</First>
    <Second>5736/ 1044</Second>
    <GPSBaseline>
      <X>-257315.3278</X>
      <Y>-177132.2020</Y>
      <Z>72229.4521</Z>
      <SigmaXX>4.9234645842511e-06</SigmaXX>
      <SigmaXY>-4.9476617405125e-06</SigmaXY>
      <SigmaXZ>3.5870089154201e-06</SigmaXZ>
      <SigmaYY>5.9422877363364e-06</SigmaYY>
      <SigmaYZ>-4.0075792893159e-06</SigmaYZ>
      <SigmaZZ>3.6216838067708e-06</SigmaZZ>
      <GPSCovariance>
        <m11>2.1543779076498e-06</m11>
        <m12>-2.2090181924519e-06</m12>
        <m13>1.5614892475095e-06</m13>
        <m21>-2.2204912680182e-06</m21>
        <m22>2.7192687935366e-06</m22>
        <m23>-1.7916043608116e-06</m23>
        <m31>1.5709218869882e-06</m31>
        <m32>-1.7978871990028e-06</m32>
        <m33>1.5723299808918e-06</m33>
      </GPSCovariance>
      <GPSCovariance>
        <m11>2.1389478433561e-06</m11>
        <m12>-2.2028922476030e-06</m12>
        <m13>1.5497212900702e-06</m13>
        <m21>-2.2105451805728e-06</m21>
        <m22>2.7098577274077e-06</m22>
        <m23>-1.7861330705486e-06</m23>
        <m31>1.5576179571336e-06</m31>
        <m32>-1.7891954217320e-06</m32>
        <m33>1.5611666604546e-06</m33>
      </GPSCovariance>
    </GPSBaseline>
    <First>5035/ 1002</First>
    <Second>ADE1</Second>
    <GPSBaseline>
      <X>-369600.5068</X>
      <Y>-647255.2497</Y>
      <Z>-305982.6306</Z>
      <SigmaXX>4.1175470246280e-06</SigmaXX>
      <SigmaXY>-3.8036107086400e-06</SigmaXY>
      <SigmaXZ>2.8795518103773e-06</SigmaXZ>
      <SigmaYY>4.4193284801433e-06</SigmaYY>
      <SigmaYZ>-2.9507324496927e-06</SigmaYZ>
      <SigmaZZ>2.8187922506569e-06</SigmaZZ>
      <GPSCovariance>
        <m11>2.5183962559475e-06</m11>
        <m12>-2.6368742844305e-06</m12>
        <m13>1.8280900737335e-06</m13>
        <m21>-2.6142920156305e-06</m21>
        <m22>3.2168253915378e-06</m22>
        <m23>-2.1095347085263e-06</m23>
        <m31>1.8123729275216e-06</m31>
        <m32>-2.0993368497363e-06</m32>
        <m33>1.7735637470013e-06</m33>
      </GPSCovariance>
    </GPSBaseline>
    <First>5035/ 1002</First>
    <Second>ALIC</Second>
    <GPSBaseline>
      <X>-482470.3938</X>
      <Y>98505.3647</Y>
      <Z>762132.6188</Z>
      <SigmaXX>3.4617613665480e-06</SigmaXX>
      <SigmaXY>-3.4655478934442e-06</SigmaXY>
      <SigmaXZ>2.3110728927928e-06</SigmaXZ>
      <SigmaYY>4.2385605091455e-06</SigmaYY>
      <SigmaYZ>-2.6188518390351e-06</SigmaYZ>
      <SigmaZZ>2.2545453054134e-06</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
  <!-- Type (G) GPS baseline -->
  <DnaMeasurement>
    <Type>G</Type>
    <Source>SANEW</Source>
    <Ignore/>
    <ReferenceFrame>ITRF1992</ReferenceFrame>
    <Epoch>03.08.1992</Epoch>
    <Vscale>1.000</Vscale>
    <Pscale>100.000</Pscale>
    <Lscale>100.000</Lscale>
    <Hscale>200.000</Hscale>
    <First>ALIC</First>
    <Second>AU001</Second>
    <GPSBaseline>
      <X>2981.7290</X>
      <Y>-2666.8400</Y>
      <Z>-9000.4630</Z>
      <SigmaXX>1.7457261805000e-06</SigmaXX>
      <SigmaXY>-1.0335401280000e-06</SigmaXY>
      <SigmaXZ>9.1178422963000e-07</SigmaXZ>
      <SigmaYY>1.4855548902000e-06</SigmaYY>
      <SigmaYZ>-8.8699137178000e-07</SigmaYZ>
      <SigmaZZ>8.9829335174000e-07</SigmaZZ>
    </GPSBaseline>
  </DnaMeasurement>
</DnaXmlFormat>
